apiVersion: apps/v1
kind: Deployment
metadata:
  name: medhistory-service
  labels:
    app: medhistory-service
  namespace: healthcare-rx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medhistory-service
  template:
    metadata:
      labels:
        app: medhistory-service
    spec:
      containers:
      - name: medhistory-service
        image: oitgaden/medhistoryservice:2.0
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
