apiVersion: apps/v1
kind: Deployment
metadata:
  name: rx-producer-deployment
  labels:
    app: rx-producer
  namespace: healthcare-rx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rx-producer
  template:
    metadata:
      labels:
        app: rx-producer
    spec:
      containers:
      - name: rx-producer
        image: oitgaden/rxproducer:1.0
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
